import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import Sidebar from '@/components/Sidebar';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';
import { fakeGetCaseDetails, fakeUploadSideA, fakeUploadSideB, fakeGetVerdict, fakeSubmitArgument } from '@/services/fakeApi';
import { Scale, ArrowLeft, Upload } from 'lucide-react';

const Hearing = () => {
  const { caseId } = useParams();
  const [caseData, setCaseData] = useState<any>(null);
  const [sideAText, setSideAText] = useState('');
  const [sideADoc, setSideADoc] = useState('');
  const [sideBText, setSideBText] = useState('');
  const [sideBDoc, setSideBDoc] = useState('');
  const [verdict, setVerdict] = useState('');
  const [newArgument, setNewArgument] = useState('');
  const [loading, setLoading] = useState(false);
  const user = JSON.parse(localStorage.getItem('user') || '{}');

  useEffect(() => {
    loadCase();
  }, [caseId]);

  const loadCase = async () => {
    try {
      const data = await fakeGetCaseDetails(caseId!);
      setCaseData(data);
      if (data.verdict) setVerdict(data.verdict);
    } catch (error) {
      toast.error('Failed to load case');
    }
  };

  const handleSideASubmit = async () => {
    if (!sideAText) {
      toast.error('Please enter case text');
      return;
    }
    setLoading(true);
    try {
      await fakeUploadSideA(caseId!, {
        caseText: sideAText,
        documentName: sideADoc || 'Text Submission',
        submittedBy: user.name
      });
      toast.success('Side A submission uploaded');
      setSideAText('');
      setSideADoc('');
      loadCase();
    } catch (error) {
      toast.error('Upload failed');
    } finally {
      setLoading(false);
    }
  };

  const handleSideBSubmit = async () => {
    if (!sideBText) {
      toast.error('Please enter case text');
      return;
    }
    setLoading(true);
    try {
      await fakeUploadSideB(caseId!, {
        caseText: sideBText,
        documentName: sideBDoc || 'Text Submission',
        submittedBy: user.name
      });
      toast.success('Side B submission uploaded');
      setSideBText('');
      setSideBDoc('');
      loadCase();
    } catch (error) {
      toast.error('Upload failed');
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateVerdict = async () => {
    setLoading(true);
    try {
      const newVerdict = await fakeGetVerdict(caseId!);
      setVerdict(newVerdict);
      toast.success('Verdict generated by AI Judge');
      loadCase();
    } catch (error) {
      toast.error('Failed to generate verdict');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmitArgument = async (side: 'A' | 'B') => {
    if (!newArgument) {
      toast.error('Please enter an argument');
      return;
    }
    if (caseData.arguments.length >= 5) {
      toast.error('Maximum 5 arguments reached');
      return;
    }
    setLoading(true);
    try {
      await fakeSubmitArgument(caseId!, newArgument, side);
      toast.success('Argument submitted');
      setNewArgument('');
      loadCase();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to submit argument');
    } finally {
      setLoading(false);
    }
  };

  if (!caseData) {
    return (
      <div className="flex h-screen bg-background">
        <Sidebar />
        <div className="flex-1 flex items-center justify-center">
          <p className="text-muted-foreground">Loading hearing...</p>
        </div>
      </div>
    );
  }

  const isLawyerA = caseData.lawyerA === user.id;
  const isLawyerB = caseData.lawyerB === user.id;
  const argumentsLeft = 5 - caseData.arguments.length;

  return (
    <div className="flex h-screen bg-background">
      <Sidebar />
      <div className="flex-1 overflow-auto">
        <div className="p-6 max-w-7xl mx-auto">
          {/* Header */}
          <div className="mb-6">
            <Link to={`/cases/${caseId}`} className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground mb-4">
              <ArrowLeft className="h-4 w-4" />
              Back to Case
            </Link>
            <div className="text-center">
              <h1 className="text-3xl font-bold text-foreground mb-1">AI Judge and its verdict</h1>
            </div>
          </div>

          {/* Verdict Box - Centered at Top */}
          <div className="mb-6">
            <Card className="border-2 border-border shadow-sm">
              <CardContent className="p-8">
                {!verdict ? (
                  <div className="text-center py-8">
                    <p className="text-muted-foreground mb-6">Click "Generate Verdict" below after both sides submit</p>
                    <Button
                      size="lg"
                      onClick={handleGenerateVerdict}
                      disabled={loading}
                      className="px-8"
                    >
                      {loading ? 'Generating Verdict...' : 'Generate AI Verdict'}
                    </Button>
                  </div>
                ) : (
                  <div>
                    <h2 className="text-xl font-bold mb-4 text-center">Verdict:</h2>
                    <div className="bg-muted/50 p-6 rounded border border-border max-h-96 overflow-y-auto">
                      <div className="whitespace-pre-line text-sm leading-relaxed">
                        {verdict}
                      </div>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Two-Column Upload Section */}
          <div className="grid md:grid-cols-2 gap-6 mb-8">
            {/* Left: Side A Upload */}
            <Card className="border-2 border-border">
              <CardContent className="p-6 space-y-4">
                <h3 className="font-bold text-lg">Upload documents here:</h3>
                
                <div>
                  <p className="font-medium mb-2">1. text</p>
                  <Textarea
                    placeholder="Enter your case arguments and evidence..."
                    rows={10}
                    value={sideAText}
                    onChange={(e) => setSideAText(e.target.value)}
                    disabled={!isLawyerA}
                    className="resize-none"
                  />
                </div>
                
                <div>
                  <p className="font-medium mb-2">2. file(s)</p>
                  <Input
                    type="file"
                    disabled={!isLawyerA}
                    className="cursor-pointer"
                  />
                  <p className="text-xs text-muted-foreground mt-2">
                    Or enter document reference:
                  </p>
                  <Input
                    placeholder="Document name..."
                    value={sideADoc}
                    onChange={(e) => setSideADoc(e.target.value)}
                    disabled={!isLawyerA}
                    className="mt-1"
                  />
                </div>

                <Button
                  className="w-full"
                  onClick={handleSideASubmit}
                  disabled={!isLawyerA || loading}
                >
                  <Upload className="h-4 w-4 mr-2" />
                  Submit Side A
                </Button>

                {caseData.sideASubmissions.length > 0 && (
                  <div className="pt-4 border-t">
                    <p className="text-sm font-medium mb-2">
                      Submissions: {caseData.sideASubmissions.length}
                    </p>
                    <div className="space-y-2 max-h-32 overflow-y-auto">
                      {caseData.sideASubmissions.map((sub: any) => (
                        <div key={sub.id} className="p-2 bg-muted rounded text-xs">
                          <p className="font-medium">{sub.documentName}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Right: Side B Upload */}
            <Card className="border-2 border-border">
              <CardContent className="p-6 space-y-4">
                <h3 className="font-bold text-lg">Upload documents here:</h3>
                
                <div>
                  <p className="font-medium mb-2">1. text</p>
                  <Textarea
                    placeholder="Enter your case arguments and evidence..."
                    rows={10}
                    value={sideBText}
                    onChange={(e) => setSideBText(e.target.value)}
                    disabled={!isLawyerB}
                    className="resize-none"
                  />
                </div>
                
                <div>
                  <p className="font-medium mb-2">2. file(s)</p>
                  <Input
                    type="file"
                    disabled={!isLawyerB}
                    className="cursor-pointer"
                  />
                  <p className="text-xs text-muted-foreground mt-2">
                    Or enter document reference:
                  </p>
                  <Input
                    placeholder="Document name..."
                    value={sideBDoc}
                    onChange={(e) => setSideBDoc(e.target.value)}
                    disabled={!isLawyerB}
                    className="mt-1"
                  />
                </div>

                <Button
                  className="w-full"
                  onClick={handleSideBSubmit}
                  disabled={!isLawyerB || loading}
                >
                  <Upload className="h-4 w-4 mr-2" />
                  Submit Side B
                </Button>

                {caseData.sideBSubmissions.length > 0 && (
                  <div className="pt-4 border-t">
                    <p className="text-sm font-medium mb-2">
                      Submissions: {caseData.sideBSubmissions.length}
                    </p>
                    <div className="space-y-2 max-h-32 overflow-y-auto">
                      {caseData.sideBSubmissions.map((sub: any) => (
                        <div key={sub.id} className="p-2 bg-muted rounded text-xs">
                          <p className="font-medium">{sub.documentName}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Post-Decision Arguments Section */}
          {verdict && (
            <Card className="border-2 border-border">
              <CardHeader>
                <CardTitle className="text-xl">Post Decision by AI</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Submit New Argument */}
                {argumentsLeft > 0 && (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <h3 className="font-semibold">Submit Counter-Argument</h3>
                      <Badge variant="outline">
                        {argumentsLeft}/5 remaining
                      </Badge>
                    </div>
                    
                    <div>
                      <p className="font-medium mb-2">1. Arguments</p>
                      <Textarea
                        placeholder="Submit your counter-argument here..."
                        rows={4}
                        value={newArgument}
                        onChange={(e) => setNewArgument(e.target.value)}
                      />
                    </div>
                    
                    <div>
                      <p className="font-medium mb-2">2. Counterarguments</p>
                      <p className="text-sm text-muted-foreground italic">(as texts)</p>
                    </div>
                    
                    <div className="flex gap-3">
                      {isLawyerA && (
                        <Button
                          className="flex-1"
                          onClick={() => handleSubmitArgument('A')}
                          disabled={loading}
                        >
                          Submit as Side A
                        </Button>
                      )}
                      {isLawyerB && (
                        <Button
                          className="flex-1"
                          onClick={() => handleSubmitArgument('B')}
                          disabled={loading}
                        >
                          Submit as Side B
                        </Button>
                      )}
                    </div>
                  </div>
                )}

                {/* Arguments History */}
                {caseData.arguments.length > 0 && (
                  <div className="space-y-4 pt-6 border-t">
                    <h3 className="font-semibold text-lg">Previous Arguments & Judge Responses</h3>
                    {caseData.arguments.map((arg: any, idx: number) => (
                      <div key={arg.id} className="border rounded-lg p-4 space-y-3 bg-muted/30">
                        <div className="flex items-center gap-2">
                          <Badge className={arg.side === 'A' ? 'bg-blue-600' : 'bg-orange-600'}>
                            Side {arg.side}
                          </Badge>
                          <span className="text-sm text-muted-foreground">
                            Round {idx + 1}
                          </span>
                        </div>
                        <div className="p-3 bg-background rounded">
                          <p className="text-sm font-medium mb-1">Argument:</p>
                          <p className="text-sm">{arg.content}</p>
                        </div>
                        <div className="p-3 bg-primary/5 rounded border border-primary/20">
                          <p className="text-sm font-medium mb-1 flex items-center gap-2">
                            <Scale className="h-4 w-4 text-primary" />
                            Judge Response:
                          </p>
                          <p className="text-sm">{arg.judgeResponse}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
};

export default Hearing;
